CREATE TABLE `article` (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name VARCHAR(256) NOT NULL,
	category VARCHAR(256) NOT NULL,
	author VARCHAR(256) NOT NULL,
	floating_nick BOOL NOT NULL DEFAULT TRUE,
	comment_count INT UNSIGNED NOT NULL
);